name: dev_quizz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  shimmer: ^2.0.0
  google_sign_in: ^5.2.3
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
